### PR TITLE
Fix example building

### PR DESCRIPTION
**Pull request by davidquon**
Running `pod install` for the example project was giving this error:

```
[!] Unable to satisfy the following requirements:

- `loudspeaker (from `../`)` required by `Podfile`
- `loudspeaker (from `../`)` required by `Podfile`
- `loudspeaker (= 0.1.2)` required by `Podfile.lock`
```

Addresses issue: https://github.com/amco/loudspeaker/issues/10

This should fix running the `pod install` and being able to build, run, and test the example project.  Bonus: Removed the `Pods` directory and other Xcode related files from Git tracking.

Steps to test:
1. `cd Example`
2. `pod install`
3. Open the example workspace
4. Build and run `loudspeaker` example
5. Run `loudspeaker` tests

@adamyanalunas - Please inspect.

### CODE REVIEW

**Comment by adamyanalunas** [comment]
I'd prefer you update the `Podfile`, not just the lock file. Expecta and Specta have both hit 1.0.

```
  pod 'Specta', '~> 1.0'
  pod 'Expecta', '~> 1.0'
```

**Comment by davidquon** [comment]
> I'd prefer you update the Podfile, not just the lock file. Expecta and Specta have both hit 1.0.

No problem.  I was just trying to fix the problem trying to trying to source `loudspeaker` `0.1.2` but fair enough point.  Will fix.  :+1:

**Comment by davidquon** [comment]
@adamyanalunas - Let me know if there is anything else.

**Comment by adamyanalunas** [comment]
`pod install` completes, example works, tests pass. :shipit:

**Pull request merged**
